<template>
  <div>
    <h1>HeaderHome.vue</h1>
    <button>
      <router-link
        :to="{ name: 'user-id-profile', params: { id: 1 }, query: { lang: 'ja', page: '2' }, hash: '#next-user' }"
        active-class="link-active"
        exact
      >TestUsers</router-link>
    </button>
    <button>
      <router-link
        to="/"
        active-class="link-active"
      >TestHome</router-link>
    </button>
    <hr>
  </div>
</template>